apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app-v2
  labels:
    app: apppod
spec:
  selector:
    matchLabels:
      app: employees
      version: v2
  replicas: 1
  template:
    metadata:
      labels:
        app: employees
        version: v2
    spec:
      containers:
      - name: deployment-app
        image: 219594430677.dkr.ecr.us-east-1.amazonaws.com/apprepo:v1.2
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
        env: 
            - name: DBHOST
              value: mysqlservice.sqldb.svc.cluster.local
            - name: DBUSER
              value: root
            - name: DBPORT
              value: "3306"
            - name: DBPWD
              value: Ashmit@321