apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-db
  labels:
    app: dbpod
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: deployment-db
        image: 219594430677.dkr.ecr.us-east-1.amazonaws.com/databaserepo:v1.1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: Ashmit@321