apiVersion: v1
kind: Service
metadata:
  name: nodeportservice
  labels:
    app: apppod
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001
