apiVersion: v1
kind: Service
metadata:
  name: mysqlservice
  labels:
    app.kubernetes.io/app: dbpod
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app.kubernetes.io/app: mongo