apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
      version: v1
  template:
    metadata:
      labels:
        app: employees
        version: v1
    spec:
      containers:
        - name: appcontainer
          image: 219594430677.dkr.ecr.us-east-1.amazonaws.com/apprepo:v1.1
          ports:
            - containerPort: 8080
          env: 
            - name: DBHOST
              value: mysqlservice.sqldb.svc.cluster.local
            - name: DBUSER
              value: root
            - name: DBPORT
              value: "3306"
            - name: DBPWD
              value: Ashmit@321
